version: '3'
services:
  jenkins:
    image: 'bitnami/jenkins:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '8888:8080'
      - '443:8443'
      - '50001:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
volumes:
  jenkins_data:
    driver: local
